### ISSUE TITLE
yellow/black bin lid overlaps causing z-fighting

### ISSUE THREAD

**Issue by hunnybear** [tribesthatmaybe/modpack#13]
Need to fix the texture so that it doesn't overlap when closed
![image](https://user-images.githubusercontent.com/882671/85558604-e3ffdd00-b5f6-11ea-8427-d9205e729e06.png)

**Comment by hunnybear** [comment]
not sure how to assign to myself, but this is mine

**Comment by hunnybear** [comment]
sorry for slowness, I've been chemo sick all weekend

**Comment by otakup0pe** [comment]
it's art;  there are no obligations here friend ☠️ 💖 

hope you are feeling better

**Comment by hunnybear** [comment]
Fixed in [3f9d1a8](https://github.com/tribesthatmaybe/modpack/commit/3f9d1a8aea7ae3c6db3c1a291d974dab40339fa7)
