### ISSUE TITLE
spawn command takes you to overworld

### ISSUE THREAD

**Issue by otakup0pe** [tribesthatmaybe/modpack#16]
I kinda want to just pull the command in favor of "magical realism" but at the least we should try and have it take you to block rock desert spawn.

**Comment by otakup0pe** [comment]
Ended up just disabling the `/spawn` command, which I think is appropriate. Thoughts @Vivrik @ziz?

**Comment by ziz** [comment]
Leaving `/home` in place? Yeah, removing `/spawn` seems perfectly reasonable.

**Comment by otakup0pe** [comment]
Not planning on it, just making waystones more accessible instead

**Comment by Vivrik** [comment]
I think /home should be maintained.
Enabling "free" back and forth travel early on seems like a bit much in lieu of a one-way "escape/return" option.
Maybe we could bump the xp consumption to 5l instead of 3l if we're making it accessible earlier?
Also, I'm not aware of other means of teleportation, so balance here could be tricky.

**Comment by otakup0pe** [comment]
I pulled the various cyclic ender items which allow easy / cheap teleportation. Mekanism does have a late game teleporter. We could also conceptually allow `/home` until a certain level / achievement is achieved and then gate it out based on the `ranks.json` stuff.

In the mean time I'll make some changes to the default waystone config to help balance it out a bit.

**Comment by otakup0pe** [comment]
Added [`Waystones.cfg`](https://github.com/tribesthatmaybe/modpack/blob/mainline/src/config/Waystones.cfg). Highlights are

* travel costs 1 level of xp per 160 blocks and caps out at ten levels - default was 1 level per 500 blocks capping out at 3
* dimensional travel costs 5 levels instead of 3
* lower chance of waystones generating in villages

**Comment by otakup0pe** [comment]
actually additions also has a "teleport staff"

we could also give players some warp scrolls which can be used to tie into a waystone as well.

**Comment by otakup0pe** [comment]
Closing this out. Non-single-use / non waystone teleport things are gated on a magic skill level of 28.
