### ISSUE TITLE
"Such a User..." quest should reflect that narrator can be rebound

### ISSUE THREAD

**Issue by ziz** [tribesthatmaybe/modpack#17]
https://github.com/tribesthatmaybe/modpack/blob/86b905542c5697c681cfb9d63a74b61fc6e8524e/src/config/betterquesting/DefaultQuests.json#L3002

The narrator can be rebound since 94d98fc and the quest should be updated to reflect that.

**Comment by Vivrik** [comment]
Deleted passage in question and adjusted following text to account for narrative gap.
Updated both default quest line and personal work file to reflect this.
