### ISSUE TITLE
build process should be able to create unique versions

### ISSUE THREAD

**Issue by ziz** [tribesthatmaybe/modpack#19]
It would be very nice for `make client` and the build actions and similar to create unique version numbers, to ease the turnaround on dev work while updating the modpack 

Possibly using the date and/or `git describe`. Even better if they're semver compatible - see https://github.com/eins78/git-describe-semver for one example of how to turn describe output into semver compatible output, though it doesn't use the date.

**Comment by otakup0pe** [comment]
![image](https://user-images.githubusercontent.com/254586/86159944-f038de00-babf-11ea-9861-00489c8a62c3.png)

ayyyyyy

**Comment by otakup0pe** [comment]
note this is only the first step. the next step will come when we start doing pull requests and junk. at that point i'll integrate the "auto bump" part of `avakas` so that we can do proper releases.
