### ISSUE TITLE
Booze Thirst & Poison Chance

### ISSUE THREAD

**Issue by Vivrik** [tribesthatmaybe/modpack#21]
Need to get item ids and determine values for alcohol "thirst" and "poisonChance".
Current thoughts;
poisonChance:.3
thirst:10 (equivalent to rice crackers)

**Comment by otakup0pe** [comment]
Need to test the thirst of rice crackers too heh.

**Comment by otakup0pe** [comment]
Rice crisypy treats and crackers will increase your thirst, everything else has been tuned "appropriately" . Only a few types of have the base poison chance.
