### ISSUE TITLE
enter via d-lot

### ISSUE THREAD

**Issue by otakup0pe** [tribesthatmaybe/modpack#23]
We need an appropriate spawn point. The vibe on discord is it should be loosely modeled after the d-lot operational area from the gerlach regional burn. It should include

* decent amount of fresh (if not purified) water
* clearly visible signs giving people who have not played minecraft before some idea of how to play this terrible game
* cones and delineators
* more cones and delineators
* some kind of command block / dispenser based mechanisms for receiving critical items (quest book, ??)

**Comment by otakup0pe** [comment]
First cut of `spawn_lot` structure is up. Need to figure out how to not have it mix with villages even though the outcome is fucking hilarious.

![image](https://user-images.githubusercontent.com/254586/86629780-c03a8080-bf80-11ea-8380-a70fc1bb5532.png)

**Comment by otakup0pe** [comment]
Threw a bunch of vehicles in there as well, although they do not have fuel. Players will still need to find the `fuel_cache` structure (or jerry cans in loot boxes or whatever)

**Comment by otakup0pe** [comment]
Another issue is that sometimes the spawn just doesn't happen? Seems to be related to an intersection between jed and rc. 

https://github.com/Ivorforce/RecurrentComplex/issues/319

**Comment by Vivrik** [comment]
Next time you're playing, import "VDLot".
It's more of an ingress area I threw together and saved in ReCom, but it should be a decent starting point. Plus, it's got lever-activated traffic control arms! :D
Also, it fits within a 32x32 space so it doesn't cross the threshold ReCom apparently has trouble with.

**Comment by otakup0pe** [comment]
Will check it out! I wasn't able to get the traffic control arms working when I played with them last.

**Comment by otakup0pe** [comment]
Looks like people have good luck with [worldprimer](https://www.curseforge.com/minecraft/mc-mods/world-primer) to force spawn configs. Could alternatively use jed's schematic spawn support, but worldprimer gets us more things.

**Comment by otakup0pe** [comment]
Fucked around a bunch and I'm relatively happy with how it looks now? It will still occasionally intersect with a village but whatever; burners do ruin everything. Need to add more "educational" content but otherwise we good.

**Comment by otakup0pe** [comment]
calling this done. will flesh out the "orientation" command blocks.
