### ISSUE TITLE
proper releases

### ISSUE THREAD

**Issue by otakup0pe** [tribesthatmaybe/modpack#30]
We currently have basic semver dev builds thanks to #19 although it does need a bit of work with #22 

As the pack gets more stable, we will lock down the `mainline` branch. At that point work will happen via pull request. Upon tagged merges to `mainline` which contain "magic bump words" in commit messages, the version will get bumped and a new build will get kicked off.

These should be the builds we distribute.

**Comment by otakup0pe** [comment]
This should probably block #26  (curseforge presence)

**Comment by ziz** [comment]
To clarify my understanding: does this mean we'll create (git term-of-art) annotated tags, or does this mean we'll make commits that have specific keyphrases in them which the build system will look for?

My general preference, absent other input, is for a system that uses tags for releases, for ease of finding those points again in the future, so I'd like to make sure my assumptions are aligned with yours.

**Comment by otakup0pe** [comment]
`avakas` handles the creation of tags and keys off of them for generating proper version bumps. so each "release" artifact would have an associated tag.

**Comment by otakup0pe** [comment]
- [x] introduce auto bump bits (can crib from [avakas](https://github.com/otakup0pe/avakas/blob/mainline/.github/workflows/build.yml#L36-L60))
- [x] update dev server on all commits to `mainline`
- [x] upload to curseforge on tagged commits to `mainline` - no build / prebuild date version bits tho
- [ ] upload all mainline builds to curseforge with build/prebuild bits as needed
- [x] introduce branch protection (reviewers optional, tests passing not)

**Comment by otakup0pe** [comment]
all this is done just needs docs updated. decided to not update on every mainline build.

**Comment by otakup0pe** [comment]
#68 adds the last few docs i guess 🌳
