### ISSUE TITLE
mod completion plz

### ISSUE THREAD

**Issue by otakup0pe** [tribesthatmaybe/modpack#36]
I think we are close to all the mods we need?

- [x] [wireless crafting terminal](https://www.curseforge.com/minecraft/mc-mods/wireless-crafting-terminal) for later game inventory magic
- [x] [better questing multiblock](https://www.curseforge.com/minecraft/mc-mods/bq-multiblock-structure-integration) for mutliblock / reurrent complex quests
- [x] [abyssalcraft](https://www.curseforge.com/minecraft/mc-mods/abyssalcraft) for some quasi eldrich content
- [x] [potioncore](https://www.curseforge.com/minecraft/mc-mods/potion-core) for more potions tho
- [x] [just enough resources](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer) where are the rocks

**Comment by Vivrik** [comment]
It's a hell of a good start.
We can always tweak, add, and prune as we go.
No need to deem anything "complete" or "permanent" for the moment being, yeah?

**Comment by otakup0pe** [comment]
Adding / removing mods has changes to the worlds / save files. I'm hoping we can come to "mod complete" as part of the [first playable](https://github.com/tribesthatmaybe/modpack/milestone/1) milestone so there is an aspect of stability.

**Comment by ziz** [comment]
For the record: removing mods is a problem, adding mods is a generally more compatible change; I'd rather start with a slightly light set of mods and add some than add a bunch and decide we really would rather have not done so later.

That being said: the things we've got plus the mods you list here are everything I'm immediately aware of wanting.

**Comment by ziz** [comment]
a suggestion, having just started to play with them and WHY THE HECK DIDN'T I USE THIS BEFORE THIS IS GREAT:

https://www.curseforge.com/minecraft/mc-mods/integrated-dynamics
https://www.curseforge.com/minecraft/mc-mods/integrated-tunnels

optionally, for more interaction, but not necessary:

https://www.curseforge.com/minecraft/mc-mods/integrated-terminals
https://www.curseforge.com/minecraft/mc-mods/integrated-crafting

and for peak bullshit, attach ID stuff to the internet:

https://www.curseforge.com/minecraft/mc-mods/integrated-rest

also, relatedly, the parts of ProjectRed that are about redstone transmission and logic:

https://www.curseforge.com/minecraft/mc-mods/project-red-integration

**Comment by otakup0pe** [comment]
I'm down for `integrated-dynamics`, `integrated-tunnels`, and `integrated-rest`. The terminals/crafting bit duplicates ae2. Project red is easier than ID but can achieve the same functionality I think.

**Comment by ziz** [comment]
Yeah, I haven't tried terminals/crafting, and they seem not necessary with ae2.

Project Red related: the redstone wires do have an easy ID equivalent, but the redstone logic blocks (sequencer, comparator, timer, etc) do not, so far as I'm aware.

**Comment by ziz** [comment]
...not 6, 36. https://github.com/tribesthatmaybe/modpack/commit/792ff0c876dbd9306794f331f70c4102fa1905cf

**Comment by otakup0pe** [comment]
rest of them added in f25c3d6fc18b699cfc842a5073a1d07906e5745f
