### ISSUE TITLE
Spice of Life, Too Spicy?

### ISSUE THREAD

**Issue by Vivrik** [tribesthatmaybe/modpack#44]
Heart gain from eating new foods is so fast that a full second row of hearts can be gained in a couple hours.

Possible solutions;
Decrease number of hearts gained per instance (currently 2).
Increase number of foods necessary to be eaten for new hearts.
Both those things.

**Comment by otakup0pe** [comment]
took a [first pass](https://github.com/tribesthatmaybe/modpack/blob/mainline/src/config/solcarrot.cfg) at the configuration, how does it look?

**Comment by otakup0pe** [comment]
calling this :ok: for now
