### ISSUE TITLE
fix the title panorama shot

### ISSUE THREAD

**Issue by otakup0pe** [tribesthatmaybe/modpack#5]
i tried following [this](https://www.planetminecraft.com/blog/resource-pack-panoramas-guide-and-tips/) guide but it still looks kinda funky. probably some fov thing? Panorama shots live [here](https://github.com/tribesthatmaybe/modpack/tree/mainline/src/resources/ttmb/textures/gui/title/background)

**Comment by ziz** [comment]
As a note: using the Quark panorama generator (and setting the resolution to something reasonable like 1024) works - as long as you aren't flying in creative mode. (You could temporarily add the [NoFOV](https://www.curseforge.com/minecraft/mc-mods/nofov) mod locally to kill flying FOV changes before taking a panorama to get around this.)

**Comment by ziz** [comment]
Note for reference in re NoFOV: you need to manually set your FOV to 90 before using Quark Panorama if you're using it, since Quark's FOV change is also blocked.

**Comment by otakup0pe** [comment]
That's only relevant when taking panoramas? We gonna need a wiki lmao
