### ISSUE TITLE
tune toasts

### ISSUE THREAD

**Issue by otakup0pe** [tribesthatmaybe/modpack#7]
starting in the black rock desert you ain't gonna find any oak. so we need to pull (at least) that toast. @ziz can you think of any others we should pull?

**Comment by ziz** [comment]
probably just kick all the tutorial/recipe book toasts to the curb? tutorializing is going to be in the form of the questbook and JEI is the recipe list. (I'm fond of the advancement toasts myself.)

**Comment by otakup0pe** [comment]
`advancement toasts` being the ones which are displayed for non-quest advancements? yeah i want to keep those, and figure we'll tie lots of them to quest items.

**Comment by otakup0pe** [comment]
I think the toasts are [fine now](https://github.com/tribesthatmaybe/modpack/blob/mainline/src/config/toastcontrol.cfg), thoughts @ziz ?

**Comment by ziz** [comment]
yeah, looks like 23002a5 resolved this
