### ISSUE TITLE
worldgen lag variances

### ISSUE THREAD

**Issue by otakup0pe** [tribesthatmaybe/modpack#8]
I'm assuming it's because of all the really pretty [recurrent complex](https://minecraft-recurrent-complex.fandom.com/wiki/Guide:_Making_a_Tree) trees kicking off cascading worldgen in the overworld that makes it untenably bad. Have gotten stuck in non-stop worldgen cycles where it just doesn't recover.

Was able to tune it a bit in the block rock desert, so will need to do the same in overworld. Maybe less custom trees and just let [realistic terrain generation](https://www.curseforge.com/minecraft/mc-mods/realistic-terrain-generation) do it's thing

**Comment by otakup0pe** [comment]
Added in a chunk [pregenerator](https://www.curseforge.com/minecraft/mc-mods/chunkpregenerator) mod and tuned it a bit. That, combined with tweaking all RC trees to never spawn seems to have helped?  On my local standalone creative play, it seems to be about the same as DDSS at least.

Leaving this open a little bit in case we still get timeouts on new worlds though.

**Comment by otakup0pe** [comment]
Seems like it is still a problem.... Wonder what other structures need to be pulled.

**Comment by otakup0pe** [comment]
Wondering if https://github.com/Ivorforce/RecurrentComplex/issues/398 has any relation.....

**Comment by otakup0pe** [comment]
https://github.com/Ivorforce/RecurrentComplex/issues/155 seems to be the core issue tracking this.

seeing it in the block rock desert dimension too. may just tune down more structure generation....

**Comment by otakup0pe** [comment]
> Wondering if [Ivorforce/RecurrentComplex#398](https://github.com/Ivorforce/RecurrentComplex/issues/398) has any relation.....

Oh yeah definitely seeing this rolling around in BRD on an ATV. Stuff is spawning in hundreds of chunks away.

**Comment by otakup0pe** [comment]
Hmmmm also possible that this is at least partially due to geolosys and is considered "won't fix"

https://github.com/oitsjustjose/Geolosys/issues/18

**Comment by ziz** [comment]
I do appreciate the shade, presumably thrown with careful investigation, directed at *waves hands* the rest of the Minecraft/Forge infrastructure [here](https://github.com/oitsjustjose/Geolosys/blob/1.12.x/changelog.md#200)

> The code to prevent it is 100% solid and works, so why it's still outputting it rarely is beyond me. So I shushed it.

**Comment by otakup0pe** [comment]
Thinking of including [tick-dynamic](https://www.curseforge.com/minecraft/mc-mods/tick-dynamic), disabling the forge logs, and having some in-game messaging (via a lore sheet probably) around considerations when exploring.

It's not as bad on the server compared to the standalone, and not sure what else to do here.

**Comment by ziz** [comment]
+1 for tick-dynamic, it looks potentially pretty helpful.

**Comment by otakup0pe** [comment]
`tick-dynamic` is crashy a f

gonna call this done vOv
